const AppConfig = {
  // searchApiUrl: '/themes/custom/infinite/dummy-content/lazy-loading-article.html',
  ad_fag: 'fag',
  ad_orbyd: 'orbyd',
  amazonURLTrId: 'ins0c-21',
  articleReadedDelay: 1000,
  cleverPush: undefined,
  feedTrackingOffset: 150,
  gtmEventName: 'gtm_event',
  gtmIndexEvent: 'gtm_index_event',
  gtmIndexPosEvent: 'gtm_index_pos_event',
  hotjarId: undefined,
  initialDocumentTitle: document.title,
  initialLocation: '/',
  padding: 10,
  searchApiUrl: '/suche',
};
